# Use the official Python 3.11-alpine base image
FROM python:3.11-alpine

# Set the working directory inside the container
WORKDIR /app

# Install dependencies needed for Poetry and building Python packages
RUN apk add --no-cache curl build-base

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python -

# Copy the pyproject.toml and poetry.lock files to the working directory
COPY pyproject.toml poetry.lock ./

# Install project dependencies using Poetry
RUN poetry install --no-root --no-dev

# Copy the entire project directory (assuming it's in the same directory as the Dockerfile) to the working directory
COPY . .

# Expose the port on which the FastAPI application will run (change it to the appropriate port used by your FastAPI app)
EXPOSE 8000

# Start the FastAPI application
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
